Bugfix: call to rules_apko target from another repository was failing.
E.g. within the same workspace as rules_apko is defined, following call succeeded:

  bazel run //baseimages/linters:linters.amd64.tar

But if we had the project and all dependencies imported to another repository and try to call:

  bazel run  @base_images_repo//baseimages/linters:linters.amd64.tar

The process of building would fail with e.g.:

```
Error: failed to build layer image for "amd64": installing apk packages: error getting package dependencies: error getting repository indexes: unable to get repository index at https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz: Get "https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz": listing "bazel-out/darwin_arm64-fastbuild/bin/baseimages/linters/cache_linters.amd64/https%3A%2F%2Fdl-cdn.alpinelinux.org%2Falpine%2Fv3.18%2Fcommunity/x86_64/APKINDEX" for offline cache: open bazel-out/darwin_arm64-fastbuild/bin/baseimages/linters/cache_linters.amd64/https%3A%2F%2Fdl-cdn.alpinelinux.org%2Falpine%2Fv3.18%2Fcommunity/x86_64/APKINDEX: no such file or directory
2023/11/30 21:47:52 error during command execution: failed to build layer image for "amd64": installing apk packages: error getting package dependencies: error getting repository indexes: unable to get repository index at https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz: Get "https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz": listing "bazel-out/darwin_arm64-fastbuild/bin/baseimages/linters/cache_linters.amd64/https%3A%2F%2Fdl-cdn.alpinelinux.org%2Falpine%2Fv3.18%2Fcommunity/x86_64/APKINDEX" for offline cache: open bazel-out/darwin_arm64-fastbuild/bin/baseimages/linters/cache_linters.amd64/https%3A%2F%2Fdl-cdn.alpinelinux.org%2Falpine%2Fv3.18%2Fcommunity/x86_64/APKINDEX: no such file or directory
Target @base_images_repo//baseimages/linters:linters.amd64.tar failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

The root reason was that `apko` got too local version of the --cache-dir flag that didn't involved the workspace_root fragment.